### PR TITLE
🌐 Add Polish translation

### PR DESCRIPTION
**Pull request by anarion80**

### CODE REVIEW

**Comment by cichy1173** [comment]
Thanks for the translation. I will test it and give a review :-)

**Comment by cichy1173** [comment]
I have sent fixes here: https://github.com/anarion80/lubelog_translations/pull/1

**Comment by cichy1173** [comment]
I approve

**Comment by MorganMLGman** [comment]
I approve

**Comment by Shogun-PB** [comment]
Approve

**Pull request merged**
